r:
	gcc rgb.c pixcolor.c    -lSDL2 -lSDL2_ttf -o build/linux/rgbpicker
	gcc hsv.c pixcolor.c    -lSDL2 -lSDL2_ttf -o build/linux/hsvpicker
d:
	gcc rgb.c pixcolor.c -g -lSDL2 -lSDL2_ttf -o build/linux/rgbpicker
	gcc hsv.c pixcolor.c -g -lSDL2 -lSDL2_ttf -o build/linux/hsvpicker
